# logs:
logs:
  log_file: logs/logs.log

# artifacts:
artifacts:
  artifacts_dir: artifacts
  # data:
  data:
    data_dir: artifacts/data
    github_data: artifacts/data/github
  # vector DB:
  vectordb:
    chromadb_dir: artifacts/chromadb
  # chatdata:
  chatdata: artifacts/qa/chatdata.json

# model:
model:
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  gemini_llm: gemini-pro